### ISSUE TITLE
Running Paket commands automatically

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-vscode-paket#24]
Run `paket restore` on plugin start
Run `paket update` on `paket.dependencies` change
Run `paket install` on `paket.references` chage

Feature should be optional (enabled by default ? )
Good way of notification what's going on. (messages we have right now can be too intrusive, maybe add notification on bottom bar?)

**Comment by smoothdeveloper** [comment]
They seem like great ideas and might help greater adoption of paket but there definitely should be an option to disable it as some command can be long depending on network, the size of paket.lock, etc.

you might throw `paket generate-include-scripts` if a .fsx is open?

**Comment by baronfel** [comment]
I'd say disabled by default, but take advantage of the vscode workspace-level configuration to allow folks to enable/disable on a per-project basis.  

If it were me I'd love to have restore done automatically, but not the other two.

And also echoing @smoothdeveloper's comment about generate-include-scripts.

Also, naturally, these should only fire if paket is installed.

**Comment by forki** [comment]
I think since VS will do this as well, we should enable it on default ;-)

**Comment by Krzysztof-Cieslak** [comment]
In `1.7.0` I've added automatic running Paket Install on `paket.dependencies` or `paket.references` file save. Turned off by default. `Paket.autoInstall` in settings.
