### ISSUE TITLE
Slow to launch paket

### ISSUE THREAD

**Issue by mtnrbq** [ionide/ionide-vscode-paket#40]
Not sure where this issue belongs, however, in recent (post May) iterations of VSCode and Ionide, the initial launch of paket commands seems very slow - approximately 10 seconds before the Paket output console is displayed from cold.
Are there settings I can enable to try to determine where the slowdown is?
(I'm seeing this on all my Windows 10 machines)

**Comment by forki** [comment]
This is probably because it downloads the paket.exe. So it's expected that very first call needs a little more time.

**Comment by mtnrbq** [comment]
Makes sense - not seeing any 'action' until paket is downloaded was causing this impression for me. Thx.

**Comment by forki** [comment]
Can you please explain how you do this? 
A bit of output could probably be added

**Comment by Krzysztof-Cieslak** [comment]
Looks like before every Paket call we silently call bootstraper without printing anything to output panel https://github.com/ionide/ionide-vscode-paket/blob/master/src/paket.fs#L75

**Comment by forki** [comment]
I wonder if we should go over to magic mode with the addin

Am 28.07.2017 08:18 schrieb "Krzysztof Cieślak" <notifications@github.com>:

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `1.7.3` - we now print out bootstrapper output to standard Paket's output channel
