### ISSUE TITLE
Packet: Restore is failing after installing Ionide plugins

### ISSUE THREAD

**Issue by smarciuska** [ionide/ionide-vscode-paket#57]
I have installed brand new VS + FSharp + VSCode on Windows 10 Enterprise box. Then I have installed the following plugins: Ionide-fsharp and Ionide-Paket

Whenever I try to execute "Packet: Restore" command (tried in admin mode as well) I get the following Error:
..\.vscode\extensions\Ionide.ionide-paket-1.9.1\bin\paket.exe
Paket version 3.33.4
Paket failed with:
	Error during parsing of ..\paket.lock.
Message: Unknown package settings restriction: && (< net40) (< portable-net45+win8+wp8+wpa81)

**Comment by smarciuska** [comment]
Work around:

* Goto: C:\Users\...\.vscode\extensions\Ionide.ionide-paket-1.9.1\bin and delete all contents
* Download paket.bootstrapper.exe from https://github.com/fsprojects/Paket/releases/ and place it to the above folder
* Execute the bootstrapper and it will download the newest version of the paket

**Comment by ovatsus** [comment]
After manually updating, we notice that everytime we run the Paket: Restore command, we see a message about paket checking for the latest version, but with the version that comes out of the box in the plugin, there is no message about auto updating. 

It seems there was already a PR to update the paket version last month (https://github.com/ionide/ionide-vscode-paket/pull/54), but it wasn't released yet

**Comment by forki** [comment]
@Krzysztof-Cieslak any chance you can release a new paket ionide with updated bootstrapper?

**Comment by ovatsus** [comment]
Hit this again today on a new machine. @Krzysztof-Cieslak, can you please publish a new version of ionide-paket which includes the fix?

**Comment by forki** [comment]
I think he did. Can you please try to uninstall and reinstall the addin? Maybe something else is wrong

**Comment by ovatsus** [comment]
The last published version is still 1.9.1 from 29 January

**Comment by Krzysztof-Cieslak** [comment]
Released new version, sorry for troubles, I was sure I've released version with fixed bootstraper before.

**Comment by ovatsus** [comment]
Thanks
