### ISSUE TITLE
The extension does not work on repositories that have Paket in magic mode.

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/ionide-vscode-paket#63]
Just try it. The bootstrapper found in the extension's folder will hang forever, and only then will `.paket\paket.exe` (another bootstrapper BTW) run.

I suggest the following logic:

1. Check if the file `.paket\paket.bootstrapper.exe` exists.
2. If it does _not_:
 * Go to step 4.
3. Otherwise:
* Execute it and proceed whether it succeeds or fails (because there might be no Internet connectivity))
4. Run `.paket\paket.exe`; if exists. If it does not, fail accordingly.

**Comment by forki** [comment]
Please send a pull request

Theodore Tsirpanis <notifications@github.com> schrieb am So., 1. Juli 2018,
22:55:
