### ISSUE TITLE
Support "install per repository"

### ISSUE THREAD

**Issue by aaronpowell** [ionide/ionide-vscode-paket#65]
I'd like to have a way from the VSCode tool to perform the ["install per repository"](https://fsprojects.github.io/Paket/installation.html) steps.

This would make it easier to undertake a workflow of:

* `dotnet new`
* Open vscode
* Add `paket`

**Comment by aaronpowell** [comment]
I'm happy to have a crack at adding this feature, but I can't for the life of me work out how to dev locally on the extension :(

**Comment by forki** [comment]
I think @Krzysztof-Cieslak has a very good strategy for local dev

Aaron Powell <notifications@github.com> schrieb am Di., 14. Aug. 2018,
03:36:

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.0`
