### ISSUE TITLE
Automated dotnet restore after install?

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-paket#68]
After you run a `paket install`, you still need to manually run a dotnet restore / build to get the newly installed packages to show up. Might it be worth having an automatic dotnet restore run after the install process?

**Comment by forki** [comment]
Some however I think this is a paket bug. @matthid in theory it should not
be needed, right?

Am Fr., 7. Dez. 2018, 13:02 hat Isaac Abraham <notifications@github.com>
geschrieben:

**Comment by matthid** [comment]
I have no idea but maybe nuget creates some cache stuff in the obj directory which the tooling picks up?

**Comment by Krzysztof-Cieslak** [comment]
Haven't we been watching in FSAC for some stuff that Paket should delete/change on install, which should start new project parsing, which should result in "project not restored" response, which should start `dotnet restore` in Ionide automatically? 

Damn, this workflow....

**Comment by isaacabraham** [comment]
OK - here's a repro repo: https://github.com/isaacabraham/paket-no-restore

1. Clone the repo.
1. Run `paket install`. This will bring down Newtonsoft as well as FSharp.Core.
1. Try to e.g. `open Newtonsoft.Json` in `Program.fs`. Nothing happens.
1. Explicitly add Newtonsoft.Json to paket.references.
1. Run `paket install`. This will bring down nothing but modify the project file to reflect the ref.
1. Try to e.g. `open Newtonsoft.Json` in `Program.fs`. Nothing happens.
1. Run `dotnet restore`
1. Try to e.g. `open Newtonsoft.Json` in `Program.fs`. Intellisense is now provided.

**Comment by isaacabraham** [comment]
cc: @forki

**Comment by forki** [comment]
weLoveSpurs.fsproj - no wonder it doesn't work

**Comment by forki** [comment]
ok one reason is: Newtonsoft.Json is not in references

**Comment by isaacabraham** [comment]
@forki That's the point. Sorry I didn't explain well - let me update the steps.

**Comment by forki** [comment]
ah ok. updated steps make sense and I consider it a bug in paket.

**Comment by isaacabraham** [comment]
@forki should I raise an issue in paket main repo and link to this or?

**Comment by forki** [comment]
@isaacabraham no need. see https://github.com/fsprojects/Paket/pull/3503

**Comment by isaacabraham** [comment]
This will definitely have a positive impact. I'm amazed people haven't noticed this before - for beginners to paket + dotnet core it must be very confusing.

**Comment by forki** [comment]
please retry with latest paket. and thanks for the repro.

**Comment by isaacabraham** [comment]
Confirmed fix in 5.197.0 :-) The only "small" change would be for Ionide to refresh itself without you needing to start typing, but this is a *very* nice-to-have.

**Comment by isaacabraham** [comment]
I take it back. That does actually work!

**Comment by forki** [comment]
Yes it works because paket now nukes the assets file again. And ionide has
a filewatcher on it...

Am Mo., 18. Feb. 2019, 17:58 hat Isaac Abraham <notifications@github.com>
geschrieben:
