### ISSUE TITLE
Support DotNet CLI

### ISSUE THREAD

**Issue by robertmaxton42** [ionide/ionide-vscode-paket#82]
It would be nice if Ionide-Paket could be configured to use `dotnet paket ...` instead of the outdated `.paket/paket.exe` call. 

  OS: Windows 10
  Ionide version: 4.5.0 
  Ionide-Paket version: 1.12.0
  VSCode version: 1.42.1
  dotnet SDK version: 3.1.101

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `2.0`
