### ISSUE TITLE
Can't run Paket Install or Restore

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-paket#83]
1. Create an empty folder.
2. Run `paket init` from command line (empty deps file).
3. Run `paket install` from command palette.

![image](https://user-images.githubusercontent.com/1781813/75780723-31acbd00-5d5c-11ea-84c8-fec34be0cd15.png)

I have no clue why it's talking about VS Live Share!

**Comment by Krzysztof-Cieslak** [comment]
![image](https://user-images.githubusercontent.com/5427083/75785094-7ee05d00-5d63-11ea-9e70-302b1a9cfd8b.png)

**Comment by isaacabraham** [comment]
I disabled and re-enabled live share. it's now working....
