### ISSUE TITLE
Change Command System to work like Git's in vscode

### ISSUE THREAD

**Issue by cloudRoutine** [ionide/ionide-vscode-paket#9]
![](http://i.imgur.com/fkPSrBY.png)

Full text input with responsive population of valid options in the command palette

[vscode git command implementation](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/gitQuickOpen.ts#L111-L223)

**Comment by Krzysztof-Cieslak** [comment]
Implementation with current API would be too hack-y, closing for now.
